# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/en/stable/ci/index.html >
#
# Documentation:
#
# * Travis CI Embedded Builds with PlatformIO
#   < https://docs.travis-ci.com/user/integration/platformio/ >
#
# * PlatformIO integration with Travis CI
#   < http://docs.platformio.org/en/stable/ci/travis.html >
#
# * User Guide for `platformio ci` command
#   < http://docs.platformio.org/en/stable/userguide/cmd_ci.html >
#
#
# Please choice one of the following templates (proposed below) and uncomment
# it (remove "# " before each line) or use own configuration according to the
# Travis CI documentation (see above).
#


#
# Template #1: General project. Test it using existing `platformio.ini`.
#

language: python
compiler: clang
python:
    - "2.7"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

sudo: false
cache:
    directories:
        - "~/.platformio"

before_install:
    - pip install cpp-coveralls

install:
    - pip install -U platformio

before_script:

script:
    - platformio run

script:
  - platformio run #pio start end
  - cd test #test start
  - cmake .
  - make
  - cd bin
  - ./tests # tests end

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
